//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBOOK
    {
        public MBOOK()
        {
            this.PARTS = "TEXT";
            this.UNITFROM = 1;
            this.PARTFROM = 1;
            this.UNITTO = 1;
            this.PARTTO = 1;
        }
    
        public long BOOKID { get; set; }
        public long LANGID { get; set; }
        public string BOOKNAME { get; set; }
        public long UNITSINBOOK { get; set; }
        public string PARTS { get; set; }
        public long UNITFROM { get; set; }
        public long PARTFROM { get; set; }
        public long UNITTO { get; set; }
        public long PARTTO { get; set; }
    }
}
