//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBOOK
    {
        public MBOOK()
        {
            this.PARTS = "TEXT";
            this.UNITFROM = 1;
            this.PARTFROM = 1;
            this.UNITTO = 1;
            this.PARTTO = 1;
        }
    
        public long BOOKID { get; set; }
        public long LANGID { get; set; }
        public string BOOKNAME { get; set; }
        public long UNITSINBOOK { get; set; }
        public string PARTS { get; set; }
        public long UNITFROM { get; set; }
        public long PARTFROM { get; set; }
        public long UNITTO { get; set; }
        public long PARTTO { get; set; }
    }
}
