//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDICTTYPE
    {
        public MDICTTYPE()
        {
            this.DICTIONARIES = new HashSet<MDICTIONARY>();
        }
    
        public long DICTTYPEID { get; set; }
        public string DICTTYPENAME { get; set; }
    
        public virtual ICollection<MDICTIONARY> DICTIONARIES { get; set; }
    }
}
