//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDICTALL
    {
        public long LANGID { get; set; }
        public long ORD { get; set; }
        public long LANGIDTO { get; set; }
        public string DICTTYPENAME { get; set; }
        public string DICTNAME { get; set; }
        public string URL { get; set; }
        public string CHCONV { get; set; }
        public string AUTOMATION { get; set; }
        public long AUTOJUMP { get; set; }
        public string DICTTABLE { get; set; }
        public string TRANSFORM_WIN { get; set; }
        public string TRANSFORM_MAC { get; set; }
        public Nullable<long> WAIT { get; set; }
        public string TEMPLATE { get; set; }
    }
}
