//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLANGUAGE
    {
        public MLANGUAGE()
        {
            this.AUTOCORRECT = new HashSet<MAUTOCORRECT>();
            this.PICBOOKS = new HashSet<MPICBOOK>();
            this.WORDSLANG = new HashSet<MWORDLANG>();
        }
    
        public long LANGID { get; set; }
        public string LANGNAME { get; set; }
        public string CHNNAME { get; set; }
        public string VOICE { get; set; }
        public Nullable<long> CURBOOKID { get; set; }
        public string ENGNAME { get; set; }
    
        public virtual ICollection<MAUTOCORRECT> AUTOCORRECT { get; set; }
        public virtual ICollection<MPICBOOK> PICBOOKS { get; set; }
        public virtual ICollection<MWORDLANG> WORDSLANG { get; set; }
    }
}
