//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLANGUAGE
    {
        public MLANGUAGE()
        {
            this.AUTOCORRECT = new HashSet<MAUTOCORRECT>();
            this.PICBOOKS = new HashSet<MPICBOOK>();
            this.WORDSLANG = new HashSet<MWORDLANG>();
        }
    
        public long LANGID { get; set; }
        public string LANGNAME { get; set; }
        public string CHNNAME { get; set; }
        public string VOICE { get; set; }
        public Nullable<long> CURBOOKID { get; set; }
        public string ENGNAME { get; set; }
    
        public virtual ICollection<MAUTOCORRECT> AUTOCORRECT { get; set; }
        public virtual ICollection<MPICBOOK> PICBOOKS { get; set; }
        public virtual ICollection<MWORDLANG> WORDSLANG { get; set; }
    }
}
