//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LollyEntities : DbContext
    {
        public LollyEntities()
            : base("name=LollyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MAUTOCORRECT> SAUTOCORRECT { get; set; }
        public virtual DbSet<MBOOK> SBOOK { get; set; }
        public virtual DbSet<MDICTIONARY> SDICTIONARY { get; set; }
        public virtual DbSet<MDICTTYPE> SDICTTYPE { get; set; }
        public virtual DbSet<MLANGUAGE> SLANGUAGE { get; set; }
        public virtual DbSet<MPHRASEUNIT> SPHRASEUNIT { get; set; }
        public virtual DbSet<MPICBOOK> SPICBOOK { get; set; }
        public virtual DbSet<MWEBEXTRACT> SWEBEXTRACT { get; set; }
        public virtual DbSet<MWEBTEXT> SWEBTEXT { get; set; }
        public virtual DbSet<MWORDUNIT> SWORDUNIT { get; set; }
        public virtual DbSet<MWORDLANG> SWORDLANG { get; set; }
        public virtual DbSet<MDICTALL> SDICTALL { get; set; }
        public virtual DbSet<MWEBTEXTALL> SWEBTEXTALL { get; set; }
    }
}
