//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    
    public partial class MPHRASELANG
    {
        public long ID { get; set; }
        public long BOOKID { get; set; }
        public long UNIT { get; set; }
        public long PART { get; set; }
        public long SEQNUM { get; set; }
        public string PHRASE { get; set; }
        public string TRANSLATION { get; set; }
        public string BOOKNAME { get; set; }
    }
}
