//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPICBOOK
    {
        public long LANGID { get; set; }
        public string BOOKNAME { get; set; }
        public string FILENAME { get; set; }
        public long NUMPAGES { get; set; }
        public long CURPAGE { get; set; }
    
        public virtual MLANGUAGE LANGUAGES { get; set; }
    }
}
