//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPICBOOK
    {
        public long LANGID { get; set; }
        public string BOOKNAME { get; set; }
        public string FILENAME { get; set; }
        public long NUMPAGES { get; set; }
        public long CURPAGE { get; set; }
    
        public virtual MLANGUAGE LANGUAGES { get; set; }
    }
}
