//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWEBEXTRACT
    {
        public string SITENAME { get; set; }
        public string TRANSFORM_WIN { get; set; }
        public string TRANSFORM_MAC { get; set; }
        public Nullable<long> WAIT { get; set; }
    }
}
