//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyShared
{
    using System;
    
    public partial class MWORDATWILL
    {
        public long ID { get; set; }
        public long SEQNUM { get; set; }
        public string WORD { get; set; }
        public string NOTE { get; set; }
    }
}
