//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
using SQLite;
using System;

namespace LollyBase
{
    public partial class LollyDB
    {
        private SQLiteConnection db = new SQLiteConnection(Properties.Settings.Default.DBPath);
    }

    [Table("AUTOCORRECT")]
    public partial class MAUTOCORRECT
    {
        [PrimaryKey]
        public int ID { get; set; }
        [NotNull]
        public int LANGID { get; set; }
        [NotNull]
        public int ORD { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string INPUT { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string EXTENDED { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string BASIC { get; set; }
    }
    [Table("BOOKS")]
    public partial class MBOOK
    {
        public MBOOK()
        {
            this.UNITFROM = 1;
            this.PARTFROM = 1;
            this.UNITTO = 1;
            this.PARTTO = 1;
        }
        [PrimaryKey]
        public int BOOKID { get; set; }
        [NotNull]
        public int LANGID { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string BOOKNAME { get; set; }
        [NotNull]
        public int UNITSINBOOK { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string PARTS { get; set; }
        [NotNull]
        public int UNITFROM { get; set; }
        [NotNull]
        public int PARTFROM { get; set; }
        [NotNull]
        public int UNITTO { get; set; }
        [NotNull]
        public int PARTTO { get; set; }
    }
    [Table("DICTALL")]
    public partial class MDICTALL
    {
        public int LANGID { get; set; }
        public int ORD { get; set; }
        public int LANGIDTO { get; set; }
        public string DICTTYPENAME { get; set; }
        public string DICTNAME { get; set; }
        public string URL { get; set; }
        public string CHCONV { get; set; }
        public string AUTOMATION { get; set; }
        public bool AUTOJUMP { get; set; }
        public string DICTTABLE { get; set; }
        public Nullable<int> WAIT { get; set; }
        public string TRANSFORM_WIN { get; set; }
        public string TRANSFORM_MAC { get; set; }
        public string TEMPLATE { get; set; }
    }
    public partial class MDICTENTITY
    {
        [PrimaryKey]
        [MaxLength(2147483647)]
        public string WORD { get; set; }
        [MaxLength(2147483647)]
        public string TRANSLATION { get; set; }
    }
    [Table("DICTIONARIES")]
    public partial class MDICTIONARY
    {
        public MDICTIONARY()
        {
            this.DICTTYPEID = 3;
            this.LANGIDTO = 1;
        }
        [NotNull]
        public int LANGID { get; set; }
        [NotNull]
        public int ORD { get; set; }
        [NotNull]
        public int DICTTYPEID { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string DICTNAME { get; set; }
        [NotNull]
        public int LANGIDTO { get; set; }
        [MaxLength(2147483647)]
        public string URL { get; set; }
        [MaxLength(2147483647)]
        public string CHCONV { get; set; }
        [MaxLength(2147483647)]
        public string AUTOMATION { get; set; }
        [NotNull]
        public int AUTOJUMP { get; set; }
        [MaxLength(2147483647)]
        public string DICTTABLE { get; set; }
        [MaxLength(2147483647)]
        public string TEMPLATE { get; set; }
    }
    [Table("DICTTYPES")]
    public partial class MDICTTYPE
    {
        [PrimaryKey]
        public int DICTTYPEID { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string DICTTYPENAME { get; set; }
    }
    [Table("LANGUAGES")]
    public partial class MLANGUAGE
    {
        [PrimaryKey]
        public int LANGID { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string LANGNAME { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string CHNNAME { get; set; }
        [MaxLength(2147483647)]
        public string VOICE { get; set; }
        public int CURBOOKID { get; set; }
        [MaxLength(2147483647)]
        public string ENGNAME { get; set; }
    }
    public partial class MPHRASELANG
    {
        public string BOOKNAME { get; set; }
        public int UNIT { get; set; }
        public int ORD { get; set; }
        public string PHRASE { get; set; }
        public string TRANSLATION { get; set; }
        public int PART { get; set; }
        public int ID { get; set; }
        public int BOOKID { get; set; }
    }
    [Table("PHRASES")]
    public partial class MPHRASEUNIT
    {
        [PrimaryKey]
        public int ID { get; set; }
        [NotNull]
        public int BOOKID { get; set; }
        [NotNull]
        public int UNIT { get; set; }
        [NotNull]
        public int PART { get; set; }
        [NotNull]
        public int ORD { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string PHRASE { get; set; }
        [MaxLength(2147483647)]
        public string TRANSLATION { get; set; }
    }
    [Table("PICBOOKS")]
    public partial class MPICBOOK
    {
        [NotNull]
        public int LANGID { get; set; }
        [PrimaryKey]
        [MaxLength(2147483647)]
        public string BOOKNAME { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string FILENAME { get; set; }
        [NotNull]
        public int NUMPAGES { get; set; }
        [NotNull]
        public int CURPAGE { get; set; }
    }
    [Table("WEBEXTRACT")]
    public partial class MWEBEXTRACT
    {
        [PrimaryKey]
        [MaxLength(2147483647)]
        public string SITENAME { get; set; }
        [MaxLength(2147483647)]
        public string TRANSFORM_WIN { get; set; }
        [MaxLength(2147483647)]
        public string TRANSFORM_MAC { get; set; }
        public int WAIT { get; set; }
    }
    [Table("WEBTEXT")]
    public partial class MWEBTEXT
    {
        [PrimaryKey]
        [MaxLength(2147483647)]
        public string SITENAME { get; set; }
        [MaxLength(2147483647)]
        public string URL { get; set; }
        [MaxLength(2147483647)]
        public string TEMPLATE { get; set; }
        [MaxLength(2147483647)]
        public string FOLDER { get; set; }
    }
    public partial class MWORDATWILL
    {
        public int ORD { get; set; }
        public int ID { get; set; }
        public string WORD { get; set; }
        public string NOTE { get; set; }
    }
    public partial class MWORDBOOK
    {
        public int ID { get; set; }
        public int BOOKID { get; set; }
        public int UNIT { get; set; }
        public int PART { get; set; }
        public int ORD { get; set; }
        public string WORD { get; set; }
        public string BOOKNAME { get; set; }
        public string NOTE { get; set; }
    }
    [Table("WORDSLANG")]
    public partial class MWORDLANG
    {
        [NotNull]
        public int LANGID { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string WORD { get; set; }
        [NotNull]
        public int LEVEL { get; set; }
    }
    public partial class MWORDLANGORBOOK
    {
        public string WORD { get; set; }
    }
    [Table("WORDSBOOK")]
    public partial class MWORDUNIT
    {
        [PrimaryKey]
        public int ID { get; set; }
        [NotNull]
        public int BOOKID { get; set; }
        [NotNull]
        public int UNIT { get; set; }
        [NotNull]
        public int PART { get; set; }
        [NotNull]
        public int ORD { get; set; }
        [MaxLength(2147483647)]
        [NotNull]
        public string WORD { get; set; }
        [MaxLength(2147483647)]
        public string NOTE { get; set; }
    }
}
