//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAUTOCORRECT
    {
        public int ID { get; set; }
        public int LANGID { get; set; }
        public int INDEX { get; set; }
        public string INPUT { get; set; }
        public string EXTENDED { get; set; }
        public string BASIC { get; set; }
    
        public virtual MLANGUAGE LANGUAGES { get; set; }
    }
}
