//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAUTOCORRECT
    {
        public long ID { get; set; }
        public long LANGID { get; set; }
        public long ORD { get; set; }
        public string INPUT { get; set; }
        public string EXTENDED { get; set; }
        public string BASIC { get; set; }
    
        public virtual MLANGUAGE LANGUAGES { get; set; }
    }
}
