//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBOOK
    {
        public MBOOK()
        {
            this.LESSONFROM = 1;
            this.PARTFROM = 1;
            this.LESSONTO = 1;
            this.PARTTO = 1;
        }
    
        public int BOOKID { get; set; }
        public int LANGID { get; set; }
        public string BOOKNAME { get; set; }
        public int NUMLESSONS { get; set; }
        public string PARTS { get; set; }
        public int LESSONFROM { get; set; }
        public int PARTFROM { get; set; }
        public int LESSONTO { get; set; }
        public int PARTTO { get; set; }
    
        public virtual MLANGUAGE LANGUAGES { get; set; }
    }
}
