//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDICTALL
    {
        public int LANGID { get; set; }
        public int INDEX { get; set; }
        public int LANGIDTO { get; set; }
        public string DICTTYPENAME { get; set; }
        public string DICTNAME { get; set; }
        public string URL { get; set; }
        public string CHCONV { get; set; }
        public string AUTOMATION { get; set; }
        public bool AUTOJUMP { get; set; }
        public string DICTTABLE { get; set; }
        public Nullable<int> WAIT { get; set; }
        public string TRANSFORM_WIN { get; set; }
        public string TRANSFORM_MAC { get; set; }
        public string TEMPLATE { get; set; }
    }
}
