//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MPHRASELESSON> SPHRASELESSON { get; set; }
        public DbSet<MWORDLESSON> SWORDLESSON { get; set; }
        public DbSet<MWORDLANG> SWORDLANG { get; set; }
        public DbSet<MAUTOCORRECT> SAUTOCORRECT { get; set; }
        public DbSet<MBOOK> SBOOK { get; set; }
        public DbSet<MDICTALL> SDICTALL { get; set; }
        public DbSet<MLANGUAGE> SLANGUAGE { get; set; }
        public DbSet<MPICBOOK> SPICBOOK { get; set; }
        public DbSet<MDICTIONARY> SDICTIONARY { get; set; }
        public DbSet<MDICTTYPE> SDICTTYPE { get; set; }
        public DbSet<MWEBEXTRACT> SWEBEXTRACT { get; set; }
        public DbSet<MWEBTEXT> SWEBTEXT { get; set; }
        public DbSet<MWEBTEXTALL> SWEBTEXTALL { get; set; }
    }
}
