//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MPHRASEUNIT> SPHRASEUNIT { get; set; }
        public DbSet<MWORDUNIT> SWORDUNIT { get; set; }
        public DbSet<MWORDLANG> SWORDLANG { get; set; }
        public DbSet<MAUTOCORRECT> SAUTOCORRECT { get; set; }
        public DbSet<MBOOK> SBOOK { get; set; }
        public DbSet<MDICTALL> SDICTALL { get; set; }
        public DbSet<MLANGUAGE> SLANGUAGE { get; set; }
        public DbSet<MPICBOOK> SPICBOOK { get; set; }
        public DbSet<MDICTIONARY> SDICTIONARY { get; set; }
        public DbSet<MDICTTYPE> SDICTTYPE { get; set; }
        public DbSet<MWEBEXTRACT> SWEBEXTRACT { get; set; }
        public DbSet<MWEBTEXT> SWEBTEXT { get; set; }
        public DbSet<MWEBTEXTALL> SWEBTEXTALL { get; set; }
        public DbSet<C_ES_CH_AA> C_ES_CH_AA { get; set; }
        public DbSet<C_ES_EN_TRADUK> C_ES_EN_TRADUK { get; set; }
        public DbSet<C_ES_EN_ULTRALINGUA> C_ES_EN_ULTRALINGUA { get; set; }
        public DbSet<C_FR_CH_FRHELPER> C_FR_CH_FRHELPER { get; set; }
        public DbSet<C_FR_EN_LAROUSSE> C_FR_EN_LAROUSSE { get; set; }
        public DbSet<C_FR_EN_NEIL_COFFEY> C_FR_EN_NEIL_COFFEY { get; set; }
        public DbSet<C_FR_EN_REVERSO> C_FR_EN_REVERSO { get; set; }
        public DbSet<C_GE_CH_OHDICT> C_GE_CH_OHDICT { get; set; }
        public DbSet<C_GE_EN_DICCIONARIOS> C_GE_EN_DICCIONARIOS { get; set; }
        public DbSet<C_GE_EN_REVERSO> C_GE_EN_REVERSO { get; set; }
        public DbSet<C_GE_EN_WORDREFERENCE> C_GE_EN_WORDREFERENCE { get; set; }
        public DbSet<C_KO_EN_GOOGLE> C_KO_EN_GOOGLE { get; set; }
        public DbSet<C_KO_EN_QUICKFIND> C_KO_EN_QUICKFIND { get; set; }
        public DbSet<C_RU_EN_ABBYY> C_RU_EN_ABBYY { get; set; }
        public DbSet<C_RU_EN_KMRU> C_RU_EN_KMRU { get; set; }
        public DbSet<C_RU_EN_REVERSO> C_RU_EN_REVERSO { get; set; }
        public DbSet<C_RU_EN_WORDREFERENCE> C_RU_EN_WORDREFERENCE { get; set; }
        public DbSet<C_SP_CH_OHDICT> C_SP_CH_OHDICT { get; set; }
        public DbSet<C_SP_EN_REVERSO> C_SP_EN_REVERSO { get; set; }
        public DbSet<C_SP_EN_SPANISHDICT> C_SP_EN_SPANISHDICT { get; set; }
        public DbSet<C_SP_EN_WORDREFERENCE> C_SP_EN_WORDREFERENCE { get; set; }
        public DbSet<C_SP_EN_YAHOO> C_SP_EN_YAHOO { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USERS> USERS { get; set; }
    }
}
