//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    
    public partial class MPHRASELANG
    {
        public string BOOKNAME { get; set; }
        public int LESSON { get; set; }
        public int INDEX { get; set; }
        public string PHRASE { get; set; }
        public string TRANSLATION { get; set; }
        public int PART { get; set; }
        public int ID { get; set; }
        public int BOOKID { get; set; }
    }
}
