//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWEBTEXT
    {
        public string SITENAME { get; set; }
        public string URL { get; set; }
        public string FOLDER { get; set; }
        public string TEMPLATE { get; set; }
    
        public virtual MWEBEXTRACT WEBEXTRACT { get; set; }
    }
}
