//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWEBEXTRACT
    {
        public string SITENAME { get; set; }
        public Nullable<int> WAIT { get; set; }
        public bool BODY { get; set; }
        public string TRANSFORM_WIN { get; set; }
        public string TRANSFORM_MAC { get; set; }
    
        public virtual MWEBTEXT WEBTEXT { get; set; }
    }
}
