//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    
    public partial class MWORDATWILL
    {
        public int ORD { get; set; }
        public int ID { get; set; }
        public string WORD { get; set; }
        public string NOTE { get; set; }
    }
}
