//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWORDLANG
    {
        public int LANGID { get; set; }
        public string WORD { get; set; }
        public int LEVEL { get; set; }
    
        public virtual MLANGUAGE LANGUAGES { get; set; }
    }
}
