//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LollyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWORDUNIT
    {
        public long ID { get; set; }
        public long BOOKID { get; set; }
        public long UNIT { get; set; }
        public long PART { get; set; }
        public long ORD { get; set; }
        public string WORD { get; set; }
        public string NOTE { get; set; }
    }
}
